---
title: "UVU Philanthropy Workshop"
author: Greg Brooks
date: 03-23-2026
format: revealjs
    scroll-view: true
    slide-number: true
    show-slide-number: print
categories:
    - Social Impact
    - Philanthropy
draft: true
---

# Philanthropy Overview

## Welcome to the workshop!

## The Prospect Research Niche + Greg's Background
- BS in Psychology
- Prospect research analyst, but more on that later
- Early-career fundraising professional
- VP at Apra Utah, a local professional org for those in my niche
- Former SIMLab contributer
- Former Impact Evaluation Fellow at the Center for Social Impact
- Yes, you can connect with me on LinkedIn (I try to post about open jobs in my field, especially in Utah)

::: {.notes}
- Psych BS: degree which I loved, but of the many classes I took, I think some of my research methods classes were the most relevant. I switched majors so much it took me ~8 years to finally finish. Don't do what I did, which was essentially spend a lot of money to learn that I don't want to be a therapist, and that running a peer support group is more than enough to occupy that impulse. 
- I was a part-time student for most of my undergraduate studies, for financial reasons, until a bipolar scholarship got me more seriously into finishing school.
- Tangent: That bipolar scholarship is a fascinating example of philanthropy, because it acknowledged how bipolar can affect your ability to graduate, complete advanced courses, etc. Not many people, including the Accessibility Office at UVU, when I went to them for help years ago, actually understand that lived experience and the accomodations that may help. (Baer Reintegration Scholarship). For example: it didn't require me to be a freshman, it allowed for a wide variety of paths, like cosmetology school, and crucially, it allowed for part-time schooling. Arguably one of the biggest gaps in our current scholarship environment are part-time scholarships, for reasons I may mention later on, but the gist of it is: major donors do not understand their value, they seem less prestigious or rigorous, they may not understand the financial situation of the average student, or they are just relying on the fundraisers and program directors for the details of the scholarship, and they default to full-time for a myriad of reasons. Unfortunately, for many things, if it looks weird to a donor, they won't fund it, and as you can imagine, the experience of a lower income student vs. a high dollar philanthropist is so disparate, that relying solely on the donor's judgement for those details is a flawed and biased way of structuring the philanthropy
- My professional background colors my opinion on philanthropy, and may make me a touch more skeptical in my tone, but that's because I believe philanthropy is surprisingly difficult to do well from a social impact perspective: if we are trying to do no harm to ourselves, interpersonally, communally, and at a broader cultural level. But a bit more on that later
- Worked as an analyst for UVU's "advancement" division (industry jargon for higher-ed fundraising), now at the University of Utah doing the same thing (though with more zeros involved with all the numbers I look at)
- SIMLab: contributed to Project READ analysis, the social impact evaluation primer, and an analysis of the impact of college counselors on student performance. Didn't make any waves, and I was arguably the dumbest guy in a room with a highly trained economist, highly competent student coders, etc. When you can, try to get into the rooms where everyone else has more skills than you do, it makes for great ambient learning and personal development.
- Easily my favorite college experience, and I think plenty of workplaces could learn important lessons about teamwork culture from what they do here at the center
- I haven't done any public speaking in a while, because my day-to-day life involves sitting at a desk in a basement muttering curse words because ResearchPoint (a fundraising database) is suffering from another service outage, so I'm attempting to make this interesting, and failing that, useful for understanding opportunites in my career path, and in fundraising as a whole.

:::

## Is philanthropy relevant to my life as a student?
- Yes, though the average student is not a high-dollar philanthropist (or connected to one via family)
- More relevant as the source of student aid (e.g. scholarships)
- Philanthropy is connected to industries where a student might find employment (e.g. fundraising)
- Your voice as a student has more weight than you might expect, especially when organized around a cause

## What is philanthropy?
- We don't need the dictionary definition. What about working definitions / use-cases?
- Tax efficient PR strategy (individual & corporate)
- Strategic means for community or legislative impact
- Fodder for a boring slide-deck if I'm not careful

## Is philanthropy effective?
- In the short term, easy to say yes
- Taking the long view, things get complicated

## Macro-trends in Charitable Giving
- Small-dollar donor participation is in steep decline (economy, wealth concentration, etc)
- Similarly, total number of donors is going down (more high-dollar donors everyone is chasing after)
- Institutional trust frequently shredded by scandal
- Your average donor who isn't a billionaire or multi-millionaire may be more compelled by one-off projects, or local programs, or things that they think have social impact that aren't explicitly philanthropy
- Elon Musk quote that is very revealing: "My businesses are my philanthropy", as in, contributing to the overall economic output of the country via enterprise translates to downstream benefits for the average person more than giving them money via philanthropic vehicles. Any reactions to that? 

# Fundraising as a career
 - 




## References
- [Community Foundation of Utah DAFs](https://utahcf.org/give/explore/donor-advised-funds)
- [Brooklyn Org - DAFs and Community Impact](https://brooklyn.org/funds/)
- [Funraise's state of fundraising 2026](https://www.funraise.org/blog/the-state-of-the-nonprofit-sector)
