---
title: Toolkit Dashboard
format: dashboard
execute: 
  enabled: false
---
```{r, setup}
#| include: false
library(DT)
library(ggplot2)
library(dplyr)
library(readr)
library(tidyverse)
library(crosstalk)
library(htmlwidgets)

```

```{r}
# save data to object
# softwarecompare_data <- data.frame(read_csv("../ProspectResearchToolkit/data/pr_tool_comparisons.csv"))
# software_term_data <- data.frame(read_csv("../ProspectResearchToolkit/data/pr_jobs_dataset_softwarefreq_10-9-25.csv"))
# prompt_library <- data.frame(read_csv("../ProspectResearchToolkit/tools/ApraUtahTools/ProspectResearch_PromptLibrary/PR_PromptLibrary_v3.csv))

# jobs <- 22

# jobtitle_pr_dataset <- data.frame(read_csv("../ProspectResearchToolkit/data/job_titles/CMAP/cleanCMAP_dataset/PRSPDEV_JobTitles_CMAP_2017_ALLSECTORS.csv"))


```


# Software Comparison

## Row

```{r}
#| title: Comparison table

datatable(softwarecompare_data)

```


# Job Descriptions / Skills

## Row
```{r}
cat("title=", "Software terms metioned in 22 analyst job descriptions gathered starting 7/2024")

datatable(software_term_data)

```

```{r}
cat("title=", "Software term chart")

ggplot(data = software_term_data, aes(x = Term, y= Frequency)) + 
geom_bar(stat = "identity", fill = "blue") +
theme(axis.text.x = element_text(angle = 45, hjust = 1))

```
# Job title dataset

## Row
```{r}
cat("title=", "Prospect Dev job titles / frequency from public CMAP dataset")
datatable(jobtitle_pr_dataset)


```
```{r}
cat("title=", "Job title chart (>10 instances)")

top_PR_titles <- jobtitle_pr_dataset[jobtitle_pr_dataset$frequency_cleaned>10,]

ggplot(data = top_PR_titles, aes(x = title_cleaned, y= frequency_cleaned)) + 
geom_bar(stat = "identity", fill = "red") +
theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


# Future dashboard elements
## Row 1

```{r}
#| content: valuebox
#| title: "Valuebox with pencil icon"
list(
  icon = "pencil",
  color = "danger",
  value = jobs
)
```
```{r}
#| content: valuebox
#| title: "Valuebox with trash icon"
list(
  icon = "trash",
  color = "danger",
  value = jobs
)
```
```{r}
#| content: valuebox
#| title: "Valuebox with chat icon"
list(
  icon = "chat",
  color = "danger",
  value = jobs
)
```

# Research LLM Prompt Library

## Row
```{r}
cat("title=", "Prospect Research prompt library")

datatable(prompt_library)

```