---
title: "Panic at the Fundraising Disco: AFP 2026 Recap"
author: Greg Brooks
date: 04/26/2026
draft: true
categories:
    - Industry Commentary
    - Paid Resources
    - Conference Recap
execute: 
  enabled: true
  error: true
---



Conference recap from the 2026 AFP blah blah blah you get it.

# Overview
First time at AFP - some sensible and useful breakout rooms, some not so much. This post is an unvarnished view of what I thought was helpful, from a prospect development perspective, not a frontline fundraiser's perspective. AFP certainly gave me insight into the water in which fundraisers swim. More suits and nice shoes, for sure, than at APRA. More books about emotional intelligence and burnout, which was interesting. 

And of course, my favorite microcosm of the whole affair: a hilariously apocalyptic banner hanging from one of the San Diego Convention Center archway's: **FUNDRAISERS CAN'T BE REPLACED** - and a breakout session called **The five types of fundraisers who will be replaced by AI**

## Keynote address
Just kidding, I skipped the keynote. Keynotes are pointless - the vestigial organ of professional conferences. Spare me.

# Break out sessions
Titles at conferences function much in the same way as YouTube clickbait, they're hooks. Not all clickbait ends up being bad content - and the exception to that rule

## Seizing The Largest Intergenerational Wealth Transfer
I wonder what prospective donors would think about using the weirdly aggressive word *seize* in relation to their wealth. Maybe the corporate connotations of that word line up closer to "sieze the day" style optimism, but casually, it certainly comes across as a shot across the bow. Minor quibble. *Leverage* might have been a better choice, but that's not as punchy - it doesn't set up the participant as a hero swooping down to seize all that Millenial and Gen X money! Capture their hearts!

But forget all that. This session was genuinely sensible, using data from the Fundraising Effectiveness Project and GivingUSA, and did not downplay the risks of America's current economic situation. 

Ultimately, I don't think that anyone can reverse the alarming economic trends that are shredding America into, I guess, a feudal system where we become war boys for the Immortan Nvidia Chief? It's unclear, but it sucks. 

But in the meantime, we can use some logic about the nature of any given organizations donor base - what needs to happen to survive. Leaders would say the word "grow", but it depends on what we are talking about - dollars may grow, but if the number of donors continues to shrink, then organizations increasingly cede power and priorities to a smaller and smaller pool of individuals - which may be at odds with the original philanthropic mission. 

Nothing new, of course, classic Gilded Age stuff. The difference is the scale, the moving parts, the technology, and the players involved.

### Rich getting richer
- $84 trillion will be passed down to the next generations (X, Millenial) over the next 20 year
- Loyal donor bases are aging, and younger donors, sometimes the recipients of intergenerational wealth transfer, are not lining up at the door to replace them
- New donors should be tracked closely, no matter their initial donation size

### Thinking differently
- Salient points about how Gen X and Millenials will require completely different messaging and stewardship than Boomers, especially in the digital marketing space
- Of course, all of the specific data points about new donors are about Australian Gen X and Millenials, which, for all I know, may be apples to oranges with America

### Old audience vs. New audience
- Finding new donors in new places - in terms of prospect research, where are Gen X and Millenials existing online that we may otherwise miss? I've never heard TikTok mentioned as a place to get donor context, and people are *always* underrating interview podcasts as a way to learn about affinity and even capacity
- Prospect researchers are never marking people as "10 years out" for solicitation, but I think that would be a fascinating example of proactive research. This was not mentioned in the session, but with all the emphasis on "Lifetime Giving" it makes me wonder how to do prospect research "across the lifetime" instead of for an individual moment or project. I'll have to dig into this deeper. Call it "The Long Game: Building a 10-years Out Potential Prospect Pool"
- "Look-alike audiences" - it seems like Prospect Research really needs to study market research in a more fundamental way, the words may be different (prospects vs. audience), but the research and reporting elements are miles ahead of what anybody in prospect research is doing
- Is prospect research just amateur, clumsy market research?
- Do any prospect research shops calculate "cost per lead"? That's a fascinating metric. If you aren't measuring how identified prospects move on into the donor giving cycle, in terms of donations, engagement, etc - then you can't give context for the "cost per lead" metric, because you essentially don't know what happens with the leads you "bought" in the first place
- Affinity grows and changes over time, affinity and "brand awareness" overlap so much, in some cases they are almost identical
- Some institutions look for prospects with a problematically simple line of logic: "To find nursing donors, we should look at nursing graduates" and then, when that turns up nothing, they move on - assuming the donors don't exist. But really, you should be creating affinity pools, informed but not limited by classic engagement and affinity anchors, and when the moment comes, diving deeper into those affinity pools. The thing about affinity pools, is that they should not put donors into one discrete lane, more likely, they are tagged with 3-10 affinity markers, and further research can clarify to what extend those markers are relevant, how they have changed over time, etc.
- It's like how credit card companies and really any company with a big customer base track user and buyer habits over the long-term. You should not necessarily assume anything, you should create your clusters from those which are statistically significant along several dimensions. For example, which affinity tags are associated with higher conversion rates from non-donor to donor, donor to major giver, or repeated giver, or frequent giver? That dynamically changes what kind of prospect research you should do for each cluster.
- what is the "cost per acquisition"? Would that be a formula including the "cost per lead generated"? So the leadgen cost added to the solicitation costs, marketing costs, and general operations costs.
- Prospect research that is focusing on desperate projects on weekly timelines, vs. yearly timelines, then the resulting research will be shallow, clumsy, and often answer questions that most people could answer if they have an hour or two with basic Googling and database skills. If prospect researchers don't want to be replaced by market research firms (it may happen no matter what, honestly) then they need to level up their technical skills to emulate how for-profit institutions do research. Business intelligence teams and prospect researchers need to talk more, and in fact, have liasons or be on the same team if possible.
- Prospect researchers do not calculate their own ROI enough, and are left out of ROI strategy conversations.

## 12-Month Guide to Capital Campaigns
- app: MyMajorGiftGetter, also a book along the same lines
- Research should run concurrently throughout the planning for a capital campaign
- "Rich streets" list, run a query on the database, find those who live on rich streets regardless of whether they are already major givers, then you can filter out those who are already managed, and for the true potential hidden gems, find the ones that have had no wealth screening or no research, they may be undervalued
- most amount of money, least amount of people, quickest period of time
- How does one get into conducting feasibility studies for consultants?
- Capital compaigns are stretch goals, not an annual campaign
- "Catch and release" - moving through donor conversations in 30 day springs, not necessarily asking for gifts "We're not ready to ask you for a gift yet." - honest and lets the potential donor have room to engage in the conversation differently, more open, more authenticity (e.g. before a tour - "We're not asking for a gift today. We just want to show we what we do, because we believe in it.")
- The Sydney Dogs & Cats grant solicitation was an amazing example: eventually went public "Thank you to the new NSW Leader of the Opposition, There's still time, current Premiere!" completely genius - bipartisan, digitally savvy
- Prospect Researcher as an investment item for a capital campaign, during a feasibility study, e.g. from Capital Campaign Pro (look into this more). 
- "donor objections" and how that influences prospect research recommendations, and maybe could be a question in portfolio strategy meetings. Donor personas need to include "anti-affinities" as well, to help with clustering? if they are statistically significant?
- Feasibility study or a planning study
- Can I make public records requests to access university feasibility studies?
- Feasibility studies should be very transparent in their findings. Where do NDAs and consultant confidentiality land for feasibility studies?
- I've never been interviewed by consultants during feasibility studies, and many people in my niche are not considered experts in the room during feasibility discussions - but I know the dirty secrets of portfolios, in terms of stagnation, metrics, and identification pipeline issues.
- Greg's question to Mark Quigley: "Feasibility studies and planning studies cannot be skipped, and identification is a notable and crucial part of the campaign planning process - and based on this presentation, runs concurrently through multiple phases, especially if it's a lengthier or more complex campaign. Could you speak to the role of prospect development professionals as experts in the room when partnering with fundraisers in some aspects of capital campaign planning?" - Mark Quigley's answer beyond identification that was interesting: lining up methodology between identification areas. Mentioned LIA methodology and mentioned that prospect dev should be involved in that process actively, meaning working with other teams, like a data or business intelligence team. More on [LIA](https://summitfundraising.co.uk/prioritise-how-to-use-the-l-i-a-model/#:~:text=Take%20your%20list%20and%20adapted,knowledge%20efficiently%20for%20future%20use.) here. Maybe we can't do "interest" yet, but can we do one of the three? Linkage? 