---
title: "toolkitdb_maintenance_chunks"
output: html_document
date: "2026-01-21"
---

```{r packages}
# packages
library(DBI)
library(tidyverse)

#setwd("/cloud/project/data/database/sqlite_toolkit") # set working directory to sqlite database folder and scripts
```

```{r csv imports}
tools_csv <- read.csv("csv_data_import/tools.csv")
companies_csv <- read.csv("csv_data_import/companies.csv")
features_csv <- read.csv("csv_data_import/features.csv")
research_datapoints_csv <- read.csv("csv_data_import/research_datapoints.csv")
research_methods_csv <- read.csv("csv_data_import/research_methods.csv")
research_obstacles_csv <- read.csv("csv_data_import/research_obstacles.csv")
research_usecases_csv <- read.csv("csv_data_import/research_usecases.csv")
universities_csv <- read.csv("csv_data_import/universities.csv")
university_tools_csv <- read.csv("csv_data_import/university_tools.csv")

```

```{r data cleaning}
names(tools_csv)[1] <- "tool_id"

# companies
names(companies_csv) <- c("company_id", "company_name", "company_type", "company_website", "company_extracolumn")

names(research_datapoints_csv) <- c("datapoint_id", "datapoint_name", "datapoint_category", "datapoint_comparison_temp", "datapoint_blank_temp")
names(research_methods_csv) <- c("research_method_id", "research_method_name", "method_category", "method_description", "related_use_cases")


```

```{r SQLite db connect}
# connect to database (will create a new .db file if path doesn't exist)
toolkit_db3 <- dbConnect(RSQLite::SQLite(), "toolkit_db3.db")
```

```{r initial tables}
# sqlite notes: not null needs to be specified explicitly for primary keys

# companies table
dbExecute(toolkit_db3, "CREATE TABLE companies (
          company_id INTEGER NOT NULL PRIMARY KEY,
          company_name TEXT,
          company_type TEXT,
          company_website TEXT,
          company_extracolumn TEXT
          );")

# tools table

# research datapoints table

# research methods table

# research obstacles table

# add the rest

```
```{r initial write}
dbWriteTable(toolkit_db3, "companies", companies_csv, append = TRUE)


```

```{r test queries}
dbGetQuery(toolkit_db2, "SELECT * FROM companies LIMIT 10;") # empty right now

```

```{r SQLite db disconnect}
DBI::dbDisconnect(toolkit_db3)


```
